export let nameArray = [
    'Filippo Ambrosini',
    'Nicole Angel',
    'Samuele Bertinelli',
    'Alyssa Callina',
    'Tecla Cassina',
    'Michele Codazzi',
    'Anna Conforti',
    'Luca Gottifredi',
    'Cristina Keily',
    'Riccardo Martinalli',
    'Tommaso Morganti',
    'Gloria Paieri',
    'Eleonora Paini',
    'Claudio Passerini',
    'Alessandro Poncia',
    'Elia Pontiggia',
    'Laura Ruffoni',
    'Jacopo Russo',
    'Giulia Sassella',
    'Nicolò Tocalli',
    'Federico Vanore',
    'Arianna Zucca',
].map(n => n.toLowerCase())